import Foundation

/// Static helpers voor FileSafe rapport-schrijving.
/// De daadwerkelijke copy-logica is verplaatst naar `FileSafeTransfer` in `FileSafeTransferManager.swift`.
enum FileSafeCopyEngine {

    // MARK: - Log schrijven

    static func writeLog(_ report: FileSafeCopyReport, to projectPath: String) throws {
        let projectURL = URL(fileURLWithPath: projectPath)
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        encoder.dateEncodingStrategy = .iso8601
        let data = try encoder.encode(report)

        // Per-transfer log: bij meerdere kaarten in hetzelfde project blijft elk
        // verificatiebewijs bewaard (voorheen overschreef import 4 die van 1-3).
        let historyDir = projectURL.appendingPathComponent(".filesafe-logs", isDirectory: true)
        try? FileManager.default.createDirectory(at: historyDir, withIntermediateDirectories: true)
        let stamped = historyDir.appendingPathComponent("\(Self.reportStamp(report)).json")
        try? data.write(to: stamped, options: .atomic)

        // Laatste run blijft op de bekende locatie staan (voor bestaande lezers)
        let logURL = projectURL.appendingPathComponent(".filesafe-log.json")
        try data.write(to: logURL, options: .atomic)
    }

    /// Unieke, sorteerbare naam per transfer: <volume>_<datum-tijd>
    private static func reportStamp(_ report: FileSafeCopyReport) -> String {
        let df = DateFormatter()
        df.dateFormat = "yyyy-MM-dd_HHmmss"
        let volume = report.volumeName
            .replacingOccurrences(of: "/", with: "_")
            .replacingOccurrences(of: " ", with: "-")
        return "\(df.string(from: report.startTime))_\(volume)"
    }

    /// Genereer een leesbaar TXT rapport in de footage-map
    static func writeTxtReport(_ report: FileSafeCopyReport, to projectPath: String, footagePath: String? = nil) throws {
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd HH:mm:ss"

        var lines: [String] = []
        lines.append("===============================================")
        lines.append("  FileSafe Verification Report")
        lines.append("===============================================")
        lines.append("")
        lines.append("Project:   \(report.projectName)")
        lines.append("Volume:    \(report.volumeName)")
        lines.append("Start:     \(dateFormatter.string(from: report.startTime))")
        lines.append("End:       \(dateFormatter.string(from: report.endTime))")
        lines.append("Duration:  \(report.formattedDuration)")
        lines.append("")
        lines.append("Total Files:  \(report.totalFiles)")
        lines.append("Total Size:   \(ByteCountFormatter.string(fromByteCount: report.totalSize, countStyle: .file))")
        lines.append("Verified:     \(report.successCount)")
        lines.append("Failed:       \(report.failCount)")
        lines.append("Warnings:     \(report.warningCount)")
        lines.append("")
        lines.append("-----------------------------------------------")
        lines.append("  File Details")
        lines.append("-----------------------------------------------")
        lines.append("")

        for result in report.results {
            let status = result.isFullyVerified ? "[OK]   " : "[FAIL] "
            let sizeCheck = result.sizesMatch ? "OK" : "FAIL"
            let checksumCheck = result.checksumsMatch ? "OK" : "FAIL"
            let bytesCheck = result.bytesMatch ? "OK" : "FAIL"

            lines.append("\(status) \(result.sourceFile.fileName)")
            lines.append("         Size: \(sizeCheck)  |  SHA-256: \(checksumCheck)  |  Bytes: \(bytesCheck)")
            lines.append("         Size: \(ByteCountFormatter.string(fromByteCount: result.sourceFile.fileSize, countStyle: .file))")
            lines.append("         -> \(result.destinationPath)")

            if result.retryCount > 0 {
                lines.append("         Retries: \(result.retryCount)")
            }
            if let error = result.error {
                lines.append("         ERROR: \(error)")
            }
            if !result.sourceChecksum.isEmpty {
                lines.append("         SHA-256: \(result.sourceChecksum)")
            }
            lines.append("")
        }

        lines.append("===============================================")
        lines.append("  Generated by FileSafe (FileFlower)")
        lines.append("  \(dateFormatter.string(from: Date()))")
        lines.append("===============================================")

        let text = lines.joined(separator: "\n")
        let sanitizedName = report.projectName.replacingOccurrences(of: "/", with: "_")

        // Schrijf naar footage-map als beschikbaar, anders projectroot
        let baseURL: URL
        if let footagePath = footagePath {
            baseURL = URL(fileURLWithPath: projectPath).appendingPathComponent(footagePath)
            try? FileManager.default.createDirectory(at: baseURL, withIntermediateDirectories: true)
        } else {
            baseURL = URL(fileURLWithPath: projectPath)
        }

        // Unieke bestandsnaam per transfer (volume + tijdstip): een tweede kaart-import
        // in hetzelfde project overschrijft het eerdere rapport nu niet meer.
        let txtURL = baseURL.appendingPathComponent("FileSafe_Report_\(sanitizedName)_\(reportStamp(report)).txt")
        try text.write(to: txtURL, atomically: true, encoding: .utf8)
    }

    /// Pad naar het TXT rapport van een specifieke transfer.
    /// Valt terug op het nieuwste rapport van dit project als het exacte bestand ontbreekt
    /// (bv. rapporten geschreven vóór de timestamp-naamgeving).
    static func txtReportPath(
        projectName: String,
        projectPath: String,
        footagePath: String? = nil,
        report: FileSafeCopyReport? = nil
    ) -> String {
        let sanitizedName = projectName.replacingOccurrences(of: "/", with: "_")
        let baseURL: URL
        if let footagePath = footagePath {
            baseURL = URL(fileURLWithPath: projectPath).appendingPathComponent(footagePath)
        } else {
            baseURL = URL(fileURLWithPath: projectPath)
        }

        if let report = report {
            let exact = baseURL.appendingPathComponent("FileSafe_Report_\(sanitizedName)_\(reportStamp(report)).txt")
            if FileManager.default.fileExists(atPath: exact.path) {
                return exact.path
            }
        }

        // Fallback: nieuwste rapport van dit project in deze map
        let prefix = "FileSafe_Report_\(sanitizedName)"
        if let contents = try? FileManager.default.contentsOfDirectory(
            at: baseURL,
            includingPropertiesForKeys: [.contentModificationDateKey],
            options: [.skipsHiddenFiles]
        ) {
            let matches = contents
                .filter { $0.lastPathComponent.hasPrefix(prefix) && $0.pathExtension == "txt" }
                .sorted { a, b in
                    let da = (try? a.resourceValues(forKeys: [.contentModificationDateKey]))?.contentModificationDate ?? .distantPast
                    let db = (try? b.resourceValues(forKeys: [.contentModificationDateKey]))?.contentModificationDate ?? .distantPast
                    return da > db
                }
            if let newest = matches.first {
                return newest.path
            }
        }

        return baseURL.appendingPathComponent("\(prefix).txt").path
    }
}
