import Foundation

/// Static helpers voor FileSafe rapport-schrijving.
/// De daadwerkelijke copy-logica is verplaatst naar `FileSafeTransfer` in `FileSafeTransferManager.swift`.
enum FileSafeCopyEngine {

    // MARK: - Log schrijven

    static func writeLog(_ report: FileSafeCopyReport, to projectPath: String) throws {
        let logURL = URL(fileURLWithPath: projectPath)
            .appendingPathComponent(".filesafe-log.json")

        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        encoder.dateEncodingStrategy = .iso8601

        let data = try encoder.encode(report)
        try data.write(to: logURL, options: .atomic)
    }

    /// Genereer een leesbaar TXT rapport in de footage-map
    static func writeTxtReport(_ report: FileSafeCopyReport, to projectPath: String, footagePath: String? = nil) throws {
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd HH:mm:ss"

        var lines: [String] = []
        lines.append("===============================================")
        lines.append("  FileSafe Verification Report")
        lines.append("===============================================")
        lines.append("")
        lines.append("Project:   \(report.projectName)")
        lines.append("Volume:    \(report.volumeName)")
        lines.append("Start:     \(dateFormatter.string(from: report.startTime))")
        lines.append("End:       \(dateFormatter.string(from: report.endTime))")
        lines.append("Duration:  \(report.formattedDuration)")
        lines.append("")
        lines.append("Total Files:  \(report.totalFiles)")
        lines.append("Total Size:   \(ByteCountFormatter.string(fromByteCount: report.totalSize, countStyle: .file))")
        lines.append("Verified:     \(report.successCount)")
        lines.append("Failed:       \(report.failCount)")
        lines.append("Warnings:     \(report.warningCount)")
        lines.append("")
        lines.append("-----------------------------------------------")
        lines.append("  File Details")
        lines.append("-----------------------------------------------")
        lines.append("")

        for result in report.results {
            let status = result.isFullyVerified ? "[OK]   " : "[FAIL] "
            let sizeCheck = result.sizesMatch ? "OK" : "FAIL"
            let checksumCheck = result.checksumsMatch ? "OK" : "FAIL"
            let bytesCheck = result.bytesMatch ? "OK" : "FAIL"

            lines.append("\(status) \(result.sourceFile.fileName)")
            lines.append("         Size: \(sizeCheck)  |  SHA-256: \(checksumCheck)  |  Bytes: \(bytesCheck)")
            lines.append("         Size: \(ByteCountFormatter.string(fromByteCount: result.sourceFile.fileSize, countStyle: .file))")
            lines.append("         -> \(result.destinationPath)")

            if result.retryCount > 0 {
                lines.append("         Retries: \(result.retryCount)")
            }
            if let error = result.error {
                lines.append("         ERROR: \(error)")
            }
            if !result.sourceChecksum.isEmpty {
                lines.append("         SHA-256: \(result.sourceChecksum)")
            }
            lines.append("")
        }

        lines.append("===============================================")
        lines.append("  Generated by FileSafe (FileFlower)")
        lines.append("  \(dateFormatter.string(from: Date()))")
        lines.append("===============================================")

        let text = lines.joined(separator: "\n")
        let sanitizedName = report.projectName.replacingOccurrences(of: "/", with: "_")

        // Schrijf naar footage-map als beschikbaar, anders projectroot
        let baseURL: URL
        if let footagePath = footagePath {
            baseURL = URL(fileURLWithPath: projectPath).appendingPathComponent(footagePath)
            try? FileManager.default.createDirectory(at: baseURL, withIntermediateDirectories: true)
        } else {
            baseURL = URL(fileURLWithPath: projectPath)
        }

        let txtURL = baseURL.appendingPathComponent("FileSafe_Report_\(sanitizedName).txt")
        try text.write(to: txtURL, atomically: true, encoding: .utf8)
    }

    /// Pad naar het TXT rapport
    static func txtReportPath(projectName: String, projectPath: String, footagePath: String? = nil) -> String {
        let sanitizedName = projectName.replacingOccurrences(of: "/", with: "_")
        let baseURL: URL
        if let footagePath = footagePath {
            baseURL = URL(fileURLWithPath: projectPath).appendingPathComponent(footagePath)
        } else {
            baseURL = URL(fileURLWithPath: projectPath)
        }
        return baseURL
            .appendingPathComponent("FileSafe_Report_\(sanitizedName).txt")
            .path
    }
}
